#!/usr/bin/env python

import json
from mastodon_recommender.tag_recommender import TagRecommender

with open("mastodon-instances.json") as f:
    instances = json.load(f)

instance_names = [instance["name"] for instance in instances]

tr = TagRecommender(instance_names)
tr.fetch_data()
result = tr.most_used_tags()

with open("tagcloud.json", "w") as f:
    json.dump(result, f)
